console.log("-----------------> 1 <-------------------");
var sweety="Sweety";
var cutie="Cutie";

console.log("Before swap:");
console.log(sweety);
console.log(cutie);
var temp=sweety;
sweety=cutie;
cutie=temp;
console.log("Aftre swap:");
console.log(sweety);
console.log(cutie);
console.log("-----------------> 2 <-------------------");
var num1=100;
var num2=200;
var num3=300;
console.log("Before Swap:");
console.log(num1);
console.log(num2);
console.log(num3);
var temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("Aftre swap:");
console.log(num1);
console.log(num2);
console.log(num3);
