var my;
var fullNme="null";
var myFullName= "Snehal";
var midName="Ramesh";
var myName ="Patil";
console.log("Before Initialization:");
console.log("Full Name:",fullNme);
console.log("FirstName:",myFullName);
console.log("Last Name:",myName);
console.log("Full Name:",myFullName,midName,myName);
var myLove="I love only JS";
console.log(myLove);
var firstName ="Snehal";
var lastName ="Patil";
var age="21";
var adress="Sangola";
var pincode="413307";
var gender="Female";
var isMarried="NO";
console.log("First Name:",firstName);
console.log("Last Name:",lastName);
console.log("Age :",age);
console.log("Adress:",adress);
console.log("Pincode:",pincode);
console.log("Gender:",gender);
console.log("Is Married:",isMarried);
