console.log("-------------------------> 1 <----------------");
var bankName;
console.log("bankname:",typeof bankName,'     ',"Data Type Of Operator:",typeof bankName);
bankName='SBI Bank';
console.log("bankname:",typeof bankName,'       ',"Data Type Of Operator:",typeof bankName);
console.log("-------------------------> 2 <-------------------");
var marks= '90%';
console.log("marks:",marks,'      ',"Data Type Of Operator:",typeof marks);
console.log("------------------------> 3 <-------------------");
var jsWorking;
console.log("Before Initialization:",jsWorking,'      ',"Data Type Of Operator:",typeof jsWorking);
var jsWorking=true;
console.log("After Initialization:",jsWorking,'         ',"Data Type Of Operator:",typeof jsWorking);
console.log("----------------------->  4  <-------------------");
console.log("a )");
var totalCount="Hundred and Seven";
console.log(" totalCount:",totalCount,'       ',"Data Type Of Operator:",typeof totalCount);
console.log("b )");
var totalCount=107;
console.log(" totalCount:",totalCount,'                 ',"Data Type Of Operator:",typeof totalCount);